### ISSUE TITLE
Choose a better name

### ISSUE THREAD

**Issue by fbbdev** [binki/autoserve#5]
I think the name `http-autodetect` could be confusing and worsen search hits, since this module is not (or not exclusively) about http.

My proposal (only a proposal, it's your module :grin:) is `autoserve`: it's cool and recognizable, it's still available, and I'd love to write (and read):

``` js
var autoserve = require('autoserve');
// ...
autoserve(app);
```

**Comment by binki** [comment]
Sorry for taking so long to check in on this!

OK. I think I get where you’re coming up with the name from: this module is about doing the correct variation of `http.createServer(app).listen()` or, more generically, about writing services which can be mounted in any environment without needing to be altered. I’ll go make this change now… hopefully…
